name: update-potd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '5 0 * * *' # 5mins after UTC 00:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Run
      run: go run main.go
    - name: Commit files
      run: |
        git config --local user.email "longfei1bot@gmail.com"
        git config --local user.name "longfei(bot)"
        git commit -m "Update POTD == $(date +%Y-%m-%d)" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
